[package]
name = "eawfoc_mod_generator"
version = "0.2.0"
edition = "2024"
rust-version = "1.85"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
colorized = "1.0.0"
inquire = "0.7.5"